name: news
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #routing
  auto_route: ^7.9.2

  #google fonts
  google_fonts: ^4.0.1

  #dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0


  dio: ^5.4.0

  #state_management
  flutter_bloc: ^8.1.3

  #logger
  pretty_dio_logger: ^1.3.1
  logging: ^1.2.0

  #internet connection checker
  internet_connection_checker: ^1.0.0+1

  #data models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5

  #functional programmings
  dartz: ^0.10.1

    #env
  flutter_dotenv: ^5.0.2
  device_info_plus: ^9.1.2
  flutter_gen: ^5.4.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  pinput: ^4.0.0
  super_rich_text: ^1.0.0
  animations: ^2.0.11
  dropdown_button2: ^2.3.9
  flutter_hooks: ^0.20.5
  flutter_animate: ^4.5.0
  rename: ^3.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  flutter_inappwebview: ^5.8.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  file_picker: ^8.0.6
  pull_to_refresh: ^2.0.0
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #generators
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  auto_route_generator: ^7.0.0
  flutter_gen_runner: ^5.3.1
  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
flutter_gen:
  output: lib/src/core/assets/
  
  integrations:
    flutter_svg: true
